builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs-20_x"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
